#!/bin/bash

HOMEDIR=/home/pi
LINKDIR=$HOMEDIR/linktest

RDOUT_ALIAS="rdout"
SYNC_ALIAS="sync"

rsync -az --delete rdout/ $RDOUT_ALIAS:$LINKDIR-rdout/
rsync -az --delete sync/ $SYNC_ALIAS:$LINKDIR-sync/
