#!/bin/bash

source etc/config

# copy directories over
rsync -az --delete sync/ $SYNC_ALIAS:$PI_SYNCDIR
rsync -az --delete rdout/ $RDOUT_ALIAS:$PI_RDOUTDIR

# install firmware
ssh $RDOUT_ALIAS "cd $PI_RDOUTDIR; ./prog_rdout"
check_retval "$?"
ssh $SYNC_ALIAS "cd $PI_SYNCDIR; ./prog_sync"
check_retval "$?"

# set ip/mac addresses
ssh $RDOUT_ALIAS "cd $PI_RDOUTDIR; ./set_ip 0"
check_retval "$?"
