#!/bin/bash
# IPBus setup
# the rdout/ and sync/ directories are copied to the pis,
# the software is compiled, and the IP/MAC address of the
# readout CTL ORMs is set.

source etc/config

# copy and compile
./etc/copy_dirs

# set IPBus ip addresses
declare -A pid_map
pids=""
boardnum=0
for rdout_pi_alias in "${rdout_pi_aliases[@]}"
do

    # set ip/mac addresses
    ssh $rdout_pi_alias "cd $pi_rdoutdir; ./set_ipbus_ip $boardnum" &
    pid="$!"

    # keep pid for later
    pid_map[$pid]="$rdout_pi_alias"
    pids="$pids $pid"

    # next board
    boardnum=$((boardnum+1))
done

# make sure everything exits ok
for pid in $pids
do
    wait "$pid"
    if [ $? -ne 0 ]
    then
        echo -e "${pid_map[$pid]}\t\033[0;91msetting ipbus ip/mac failed - check ip.log\033[0m"
    fi
done
