#!/bin/bash


# get config
source etc/config


# sync boards
for SYNC_ALIAS in "${SYNC_ALIASES[@]}"
do
    echo "$SYNC_ALIAS:"

    # stop any old executables
    ssh $SYNC_ALIAS "sudo killall $SYNC_EXE"

    # copy directories over
    rsync -az --delete sync/ $SYNC_ALIAS:$PI_SYNCDIR

    # start pi executables
    ssh $SYNC_ALIAS "cd $PI_SYNCDIR; ./run_sync"

    # make sure they are up
    ssh $SYNC_ALIAS "pgrep $SYNC_EXE"
done


# rdout boards
for RDOUT_ALIAS in "${RDOUT_ALIASES[@]}"
do
    echo "$RDOUT_ALIAS:"

    # stop any old executables
    ssh $RDOUT_ALIAS "sudo killall $RDOUT_EXE"

    # copy directories over
    rsync -az --delete rdout/ $RDOUT_ALIAS:$PI_RDOUTDIR

    # start pi executables
    ssh $RDOUT_ALIAS "cd $PI_RDOUTDIR; ./run_rdout"

    # make sure they are up
    ssh $RDOUT_ALIAS "pgrep $RDOUT_EXE"
done
