#!/bin/bash
# starts the executables on the raspberry pis

source etc/config


# stop any old executables
./stop_pi_exes


# sync boards
for SYNC_PI_ALIAS in "${SYNC_PI_ALIASES[@]}"
do
    echo "starting exe on $SYNC_PI_ALIAS:"

    # start pi executables
    ssh $SYNC_PI_ALIAS "cd $PI_SYNCDIR; ./run_sync"

    # make sure they are up
    PID=$(ssh $SYNC_PI_ALIAS "pgrep $SYNC_EXE")
    if [ -z "$PID" ]
    then
        echo "Aborting - the process on $SYNC_PI_ALIAS was not started"
        exit 1
    fi
done


# rdout boards
for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
do
    echo "starting exe on $RDOUT_PI_ALIAS:"

    # start pi executables
    ssh $RDOUT_PI_ALIAS "cd $PI_RDOUTDIR; ./run_rdout"

    # make sure they are up
    PID=$(ssh $RDOUT_PI_ALIAS "pgrep $RDOUT_EXE")
    if [ -z "$PID" ]
    then
        echo "Aborting - the process on $RDOUT_PI_ALIAS was not started"
        exit 1
    fi
done
