#!/bin/bash

# general variables
RDOUT_ALIAS="rdout"
SYNC_ALIAS="sync"
RDOUT_EXE="new_rdout.exe"
SYNC_EXE="sync_debug.exe"

# stop any old executables
ssh $SYNC_ALIAS "sudo killall $SYNC_EXE"
ssh $RDOUT_ALIAS "sudo killall $RDOUT_EXE"
