#!/bin/bash
# stops the executables on the raspberry pis

source etc/config

parallel $parallel_rdout_args "sudo pkill $rdoutexe ; pgrep $rdoutexe >> /dev/null && echo -e '\033[0;91mprocess was not killed\033[0m'"
parallel $parallel_sync_args "sudo pkill $syncexe ; pgrep $syncexe >> /dev/null && echo -e '\033[0;91mprocess was not killed\033[0m'"
