#!/bin/bash
# copy directories over and program the ORMs

source etc/config

./parallel_stop
./etc/copy_dirs

parallel $PARALLEL_SYNC_ARGS 'cd sync/ && ./prog_sync'
parallel $PARALLEL_RDOUT_ARGS 'cd rdout/ && ./prog_rdout'

#
#for SYNC_PI_ALIAS in "${SYNC_PI_ALIASES[@]}"
#do
#    echo "$SYNC_PI_ALIAS:"
#    ssh $SYNC_PI_ALIAS "cd $PI_SYNCDIR; ./prog_sync"
#    check_retval "$?"
#done
#
#for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
#do
#    echo "$RDOUT_PI_ALIAS:"
#    ssh $RDOUT_PI_ALIAS "cd $PI_RDOUTDIR; ./prog_rdout"
#    check_retval "$?"
#done
