#!/bin/bash -v

gcc -O src/new_rdout.c src/ejf_rdout.c src/ctl_orm.c src/data_orm.c src/hexbd.c src/hexbd_config.c src/spi_common.c -l bcm2835 -o bin/new_rdout.exe

gcc src/sleep.c -o bin/take_a_nap.exe

gcc -O src/pwr_cycle_fpgas.c src/ejf_rdout.c src/ctl_orm.c src/data_orm.c src/hexbd.c src/hexbd_config.c src/spi_common.c -l bcm2835 -o bin/pwr_cycle_fpgas.exe
