#!/bin/bash

source etc/config


for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
do
    echo "$RDOUT_PI_ALIAS ---------------------------------------- $RDOUT_PI_ALIAS"
    ssh $RDOUT_PI_ALIAS "tail $PI_RDOUTDIR/rdout.log"
done
