#!/bin/bash
# copy the directories over to all of the pis

source etc/config


# copy directories over
for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
do
    echo "$RDOUT_PI_ALIAS ---------------------------------------- $RDOUT_PI_ALIAS"
    ssh $RDOUT_PI_ALIAS "tail $PI_RDOUTDIR/rdout.log"
done
