#!/bin/bash

# function to check return values
check_retval () {
    if [ $1 -ne 0 ]
    then
        exit 1
    fi
}

# ssh aliases
RDOUT_PI_ALIASES=("pi2" "pi3" "pi4" "pi5")  # ssh aliases of the readout board pis
SYNC_PI_ALIASES=("piS")                     # ssh aliases of the sync board pis

# raspberry pi file/folder names
PI_RDOUTDIR="/home/pi/rdout/"               # directory to copy code into on rdout pis
PI_SYNCDIR="/home/pi/sync/"                 # directory to copy code into on sync pis
RDOUT_EXE="new_rdout"                       # name of the rdout executable
SYNC_EXE="sync_debug"                       # name of the sync executable

# program flags
RSYNC_FLAGS=(-az --delete '--filter=P *.log')
    # -az: archive & compress data
    # --delete: delete files in dest directory that aren't in source directory
    # --filter=P *.log: don't delete .log files
