#!/bin/bash
# copy the directories over to all of the pis
# and compile the software

source etc/config


# copy directories over
for rdout_pi_alias in "${rdout_pi_aliases[@]}"
do
    rsync "${rsync_flags[@]}" rdout/ $rdout_pi_alias:$pi_rdoutdir &
done

for sync_pi_alias in "${sync_pi_aliases[@]}"
do
    rsync "${rsync_flags[@]}" sync/ $sync_pi_alias:$pi_syncdir &
done
wait

# special timing hexaboard
scp timing-hexbd/hexbd_config.c $timing_rdout_alias:~/rdout/src/hexbd_config.c >> /dev/null


# compile
for rdout_pi_alias in "${rdout_pi_aliases[@]}"
do
    ssh $rdout_pi_alias "cd $pi_rdoutdir; ./compile" &
done

for sync_pi_alias in "${sync_pi_aliases[@]}"
do
    ssh $sync_pi_alias "cd $pi_syncdir; ./compile" &
done
wait

