#!/bin/bash
# check the log files and see which hexbds are connected on each rdout board

TOTAL=0

source etc/config

for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
do
    SKIROCMASK="$(ssh $RDOUT_PI_ALIAS "cat $PI_RDOUTDIR/rdout.log | grep -m 1 skiroc_mask")"
    SKIROCMASK="${SKIROCMASK:14}"
    HEXBDS="$(echo "$SKIROCMASK" | awk -F"f" '{print NF-1}')"
    echo -e "$RDOUT_PI_ALIAS:\t$SKIROCMASK ($HEXBDS hexbds)"
    TOTAL=$((TOTAL+HEXBDS))
done

echo -e "total:\t$TOTAL hexbds"
