#!/bin/bash
# copy directories over and program the ORMs

source etc/config

for SYNC_PI_ALIAS in "${SYNC_PI_ALIASES[@]}"
do
    echo "$SYNC_PI_ALIAS:"
    rsync --az --delete sync/ $SYNC_PI_ALIAS:$PI_SYNCDIR
    ssh $SYNC_PI_ALIAS "cd $PI_SYNCDIR; ./prog_sync"
    check_retval "$?"
done

for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
do
    echo "$RDOUT_PI_ALIAS:"
    rsync -az --delete rdout/ $RDOUT_PI_ALIAS:$PI_RDOUTDIR
    ssh $RDOUT_PI_ALIAS "cd $PI_RDOUTDIR; ./prog_rdout"
    check_retval "$?"
done
