#!/bin/bash

source etc/config


# power cycle
for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
do
    echo "power cycling $RDOUT_PI_ALIAS"
    # ssh $RDOUT_PI_ALIAS "cd $PI_RDOUTDIR; sudo ./bin/pwr_cycle_fpgas" &
    ssh $RDOUT_PI_ALIAS "cd $PI_RDOUTDIR; sudo ./bin/v2_pwr_cycle" &
done
wait
