#!/bin/bash

source etc/config

# copy directories over
for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
do
    rsync "${RSYNC_FLAGS[@]}" rdout/ $RDOUT_PI_ALIAS:$PI_RDOUTDIR &
done
wait

# power cycle
for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
do
    echo "$RDOUT_PI_ALIAS:"
    ssh $RDOUT_PI_ALIAS "cd $PI_RDOUTDIR; ./compile; sudo ./bin/pwr_cycle_fpgas" &
done
wait
