#!/bin/bash
# synchronize the time with between all the pis and the server

source etc/config

for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
do
    echo "$RDOUT_PI_ALIAS"
    ssh $RDOUT_PI_ALIAS "sudo date -s @`( date -u +"%s" )`"
done

for SYNC_PI_ALIAS in "${SYNC_PI_ALIASES[@]}"
do
    echo "$SYNC_PI_ALIAS"
    ssh $SYNC_PI_ALIAS "sudo date -s @`( date -u +"%s" )`"
done
