#!/bin/bash
# waits for the ORMs to show up on the network

base_ip="192.168.222."
offset=200

source etc/config

boardnum=0
for rdout_pi_alias in "${rdout_pi_aliases[@]}"
do
    ip="$base_ip$((offset+boardnum))"

    found=0
    for i in {1..30}
    do
        ping -c1 -w1 $ip &> /dev/null
        if [ $? -eq 0 ]
        then
	    found=1
            break
        fi
    done
    if [ $found -ne 1 ]
    then
        echo -e "$rdout_pi_alias\t\033[0;91m($ip) not found in 30s - exiting\033[0m"
        exit 1
    fi

    boardnum=$((boardnum+1))
done
