#!/bin/bash

gcc -c src/spi_common.c -I include/ -l bcm2835 -o obj/spi_common.o
gcc -c src/sync_orm.c -I include/ -l bcm2835 -o obj/sync_orm.o

gcc -O src/sync_debug.c obj/sync_orm.o obj/spi_common.o -I include/ -l bcm2835 -o bin/sync_debug.exe

gcc -O src/enable_triggers.c obj/sync_orm.o obj/spi_common.o -I include/ -l bcm2835 -o bin/enable_triggers.exe

gcc -O src/get_trigger_enabled.c obj/sync_orm.o obj/spi_common.o -I include/ -l bcm2835 -o bin/get_trigger_enabled.exe

gcc -O src/program_fpga.c obj/spi_common.o -I include/ -l bcm2835 -o bin/program_fpga

gcc -O src/read_board_id.c obj/spi_common.o -I include/ -l bcm2835 -o bin/read_board_id

gcc -O src/get_board_type.c obj/spi_common.o -I include/ -l bcm2835 -o bin/get_board_type

