#!/bin/bash

# SYNC ORM
echo "Programming SYNC ORM" >> prog.log
sudo ./bin/program_fpga 4 < fw/sync_orm_busy2.hex > prog.log 2>&1
if [ $? -ne 0 ]
then
    echo -e "\033[0;91mprogramming failed - check prog.log\033[0m"
    exit 1
fi
