#!/bin/bash

gcc -O src/new_rdout.c src/ejf_rdout.c src/ctl_orm.c src/data_orm.c src/hexbd.c src/hexbd_config.c src/spi_common.c -I include/ -l bcm2835 -o bin/new_rdout.exe

gcc src/sleep.c -o bin/take_a_nap.exe

gcc -O src/pwr_cycle_fpgas.c src/ejf_rdout.c src/ctl_orm.c src/data_orm.c src/hexbd.c src/hexbd_config.c src/spi_common.c -I include/ -l bcm2835 -o bin/pwr_cycle_fpgas.exe

gcc -O src/program_fpga.c src/spi_common.c -I include/ -l bcm2835 -o bin/program_fpga

gcc -O src/read_board_id.c src/spi_common.c -I include/ -l bcm2835 -o bin/read_board_id

gcc -O src/set_ip_mac_address.c src/ctl_orm.c src/spi_common.c -I include -l bcm2835 -o bin/set_ip_mac_address.exe

