#!/bin/bash -v

gcc -O src/program_fpga.c src/spi_common.c -I include/ -l bcm2835 -o bin/program_fpga

gcc -O src/set_ip_mac_address.c src/ctl_orm.c src/spi_common.c -I include -l bcm2835 -o bin/set_ip_mac_address

