#!/bin/bash
# usage: ./set_ip [BOARD NUMBER]

BOARDNUM=$1
if [ -z "$BOARDNUM" ] # indicates no argument was provided
then
    echo "usage: ./set_ipbus_ip [BOARD NUMBER]"
    exit 1
fi

# compile
./compile

# set ip address
sudo ./bin/set_ipbus_ip $BOARDNUM > ip.log 2>&1
exit $?
